"""
buildRun.py

This script automates the process of building the MiniML project using Dune,
executing a MiniML test file (`.ml`), and comparing the output against an expected
output file.

Usage:
    python run_miniml.py <input_test_file.ml> <expected_output.txt>

Steps:
1. Builds the MiniML project using Dune.
2. Runs the specified MiniML input file and captures the output to a file.
3. Compares the output to an expected output file and highlights any differences.

Assumptions:
- The MiniML executable is named `miniml.exe` and located in the current directory.
- The Dune build system is configured for the project.
"""

import subprocess
import sys

def build():
    """
    Runs the Dune build system to compile the MiniML project.
    Exits the script with an error if the build fails.
    """

    print("Building project...")
    result = subprocess.run(["dune", "build"])
    if result.returncode != 0:
        print("Build failed.")
        exit(1)

def run_miniml(input_file, output_file):
    """
    Executes the MiniML binary with the given input test file and
    redirects its output to the specified output file.

    Parameters:
    - input_file: path to the .ml file containing the MiniML test case
    - output_file: path where the output of the execution will be written
    """
    with open(output_file, 'w') as f:
        subprocess.run(["./miniml.exe", "-n", "-l", input_file], stdout=f)

def clean_content(file_path):
    """
    Reads the contents of a file and strips trailing whitespace from each line.

    Parameters:
    - file_path: path to the file to read

    Returns:
    - A list of cleaned lines
    """
    with open(file_path, 'r') as file:
        return [line.strip() for line in file.readlines()]
    
def compare_outputs(test_out, test_exp):
    """
    Compares the cleaned output of the MiniML test with the expected output.

    Parameters:
    - test_out: path to the actual output file generated by MiniML
    - test_exp: path to the expected output file

    Prints a success message if the files match, or highlights differences line by line.
    """
    test_out_lines = clean_content(test_out)
    test_exp_lines = clean_content(test_exp)

    if test_out_lines == test_exp_lines:
        print("All the tests completed successfully!")
    else:
        print("The test outputs do not match. Here are the differences:")
        for i, (out_line, exp_line) in enumerate(zip(test_out_lines, test_exp_lines)):
            if out_line != exp_line:
                print(f"Line {i+1}:")
                print(f"Expected: {exp_line}")
                print(f"Got:      {out_line}")

def main():
    """
    Entry point of the script.

    Validates command-line arguments, then builds the project,
    runs the specified test file, and compares the output to the expected result.
    """
    if len(sys.argv) != 3:
        print("Usage: python run_miniml.py <input_test_file.ml> <expected_output.txt>")
        print("Usage from plzoo directory: python ./buildRun.py src/miniml/test_exn.ml test_exp")       
        return

    input_file = sys.argv[1]
    expected_file = sys.argv[2]
    output_file = "test_out"

    build()
    run_miniml(input_file, output_file)
    compare_outputs(output_file, expected_file)

if __name__ == "__main__":
    main()
